# Generated by Django 2.0.3 on 2018-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
